### PR TITLE
Inheritance in java

### PR DESCRIPTION
**Pull request by DEBADYUTI-KARMAKAR**
Inheritance in java(Single,Multlevel,Hierarchical)

### CODE REVIEW

**Comment by DEBADYUTI-KARMAKAR** [comment]
Inheritance in java(Single,Multlevel,Hierarchical)

**Comment by DEBADYUTI-KARMAKAR** [comment]
Inheritance in java(Single,Multlevel,Hierarchical)

**Comment by DEBADYUTI-KARMAKAR** [comment]
Inheritance in java(Single,Multlevel,Hierarchical)

**Comment by DEBADYUTI-KARMAKAR** [comment]
Constructor

**Comment by RaunakMandal** [comment]
Create a new pull request

**Pull request closed without merging**
